"""Vision Intelligence Subsystem for ULTRON.

Provides framework-agnostic vision domain models, contracts, state machine, privacy semantics,
sanitized exception taxonomy, configuration management, camera capture adapter, vision frame processor,
object detection engine, temporal object tracker, scene understanding analyzer, and vision planner context builder.
"""

from app.vision.adapters.camera import CameraCaptureAdapter
from app.vision.adapters.object_detector import ObjectDetectorAdapter
from app.vision.adapters.planner_context_builder import VisionPlannerContextBuilder
from app.vision.adapters.scene_analyzer import SceneAnalyzerAdapter
from app.vision.adapters.tracker import VisionTrackerAdapter
from app.vision.adapters.yolo_onnx_detector import YOLOONNXDetector
from app.vision.base import (
    IFaceDetector,
    IMotionDetector,
    IObjectDetector,
    ISceneAnalyzer,
    IVisionCapture,
    IVisionPlannerContextBuilder,
    IVisionProcessor,
    IVisionSessionManager,
    IVisionTracker,
)
from app.vision.config import VisionConfig, create_vision_config
from app.vision.detection import (
    ObjectDetectionConfig,
    ObjectDetectionConfigurationError,
    ObjectDetectionError,
    ObjectDetectionProcessingError,
    ObjectDetectionProviderError,
    ObjectDetectionTelemetry,
    ObjectDetectionTimeoutError,
    ObjectDetectionUnavailableError,
    ObjectDetectionValidationError,
    create_object_detection_config,
)
from app.vision.exceptions import (
    SceneAnalysisConfigurationError,
    SceneAnalysisError,
    SceneAnalysisProcessingError,
    SceneAnalysisTimeoutError,
    SceneAnalysisValidationError,
    TrackingConfigurationError,
    TrackingError,
    TrackingProcessingError,
    TrackingProviderError,
    TrackingTimeoutError,
    TrackingValidationError,
    VisionCaptureError,
    VisionConfigurationError,
    VisionContextConfigurationError,
    VisionContextError,
    VisionContextProcessingError,
    VisionContextTimeoutError,
    VisionContextValidationError,
    VisionDeviceNotFoundError,
    VisionError,
    VisionProcessingError,
    VisionProcessorConfigurationError,
    VisionProcessorError,
    VisionProcessorProcessingError,
    VisionProcessorTimeoutError,
    VisionProcessorValidationError,
    VisionTimeoutError,
    VisionUnavailableError,
)
from app.vision.models import (
    VALID_VISION_STATE_TRANSITIONS,
    BoundingBox,
    FaceDetection,
    FaceLandmark,
    FrameFormat,
    InvalidVisionStateTransitionError,
    MotionEvent,
    ObjectDetection,
    PixelFormat,
    SceneEvent,
    SceneEventType,
    VisionFrame,
    VisionObservation,
    VisionPrivacy,
    VisionSessionState,
    VisionSessionStateMachine,
    VisionTelemetry,
)
from app.vision.planner_context import (
    VisionContextConfig,
    VisionContextTelemetry,
    VisionPlannerContext,
    create_vision_context_config,
)
from app.vision.processor import VisionProcessor, VisionProcessorTelemetry
from app.vision.scene import (
    DominantActivity,
    MotionLevel,
    SceneAnalysisConfig,
    SceneAnalysisTelemetry,
    SceneChange,
    SceneChangeType,
    SceneState,
    SceneSummary,
    create_scene_analysis_config,
)
from app.vision.tracking import (
    VALID_TRACK_STATE_TRANSITIONS,
    ObjectTrack,
    TrackDirection,
    TrackEvent,
    TrackEventType,
    TrackingConfig,
    TrackingTelemetry,
    TrackState,
    create_tracking_config,
)

__all__ = [
    "PixelFormat",
    "FrameFormat",
    "VisionFrame",
    "BoundingBox",
    "ObjectDetection",
    "FaceLandmark",
    "FaceDetection",
    "MotionEvent",
    "SceneEventType",
    "SceneEvent",
    "VisionTelemetry",
    "VisionPrivacy",
    "VisionSessionState",
    "InvalidVisionStateTransitionError",
    "VALID_VISION_STATE_TRANSITIONS",
    "VisionSessionStateMachine",
    "VisionObservation",
    "VisionConfig",
    "create_vision_config",
    "ObjectDetectionConfig",
    "create_object_detection_config",
    "ObjectDetectionTelemetry",
    "TrackState",
    "TrackDirection",
    "TrackEventType",
    "VALID_TRACK_STATE_TRANSITIONS",
    "ObjectTrack",
    "TrackEvent",
    "TrackingConfig",
    "TrackingTelemetry",
    "create_tracking_config",
    "SceneState",
    "MotionLevel",
    "DominantActivity",
    "SceneChangeType",
    "SceneChange",
    "SceneSummary",
    "SceneAnalysisConfig",
    "SceneAnalysisTelemetry",
    "create_scene_analysis_config",
    "VisionPlannerContext",
    "VisionContextConfig",
    "VisionContextTelemetry",
    "create_vision_context_config",
    "VisionError",
    "VisionConfigurationError",
    "VisionDeviceNotFoundError",
    "VisionCaptureError",
    "VisionProcessingError",
    "VisionTimeoutError",
    "VisionUnavailableError",
    "VisionProcessorError",
    "VisionProcessorConfigurationError",
    "VisionProcessorValidationError",
    "VisionProcessorTimeoutError",
    "VisionProcessorProcessingError",
    "ObjectDetectionError",
    "ObjectDetectionConfigurationError",
    "ObjectDetectionValidationError",
    "ObjectDetectionTimeoutError",
    "ObjectDetectionProviderError",
    "ObjectDetectionUnavailableError",
    "ObjectDetectionProcessingError",
    "TrackingError",
    "TrackingConfigurationError",
    "TrackingValidationError",
    "TrackingProcessingError",
    "TrackingTimeoutError",
    "TrackingProviderError",
    "SceneAnalysisError",
    "SceneAnalysisConfigurationError",
    "SceneAnalysisValidationError",
    "SceneAnalysisProcessingError",
    "SceneAnalysisTimeoutError",
    "VisionContextError",
    "VisionContextConfigurationError",
    "VisionContextValidationError",
    "VisionContextProcessingError",
    "VisionContextTimeoutError",
    "VisionProcessorTelemetry",
    "VisionProcessor",
    "CameraCaptureAdapter",
    "ObjectDetectorAdapter",
    "YOLOONNXDetector",
    "VisionTrackerAdapter",
    "SceneAnalyzerAdapter",
    "VisionPlannerContextBuilder",
    "IVisionCapture",
    "IVisionProcessor",
    "IObjectDetector",
    "IFaceDetector",
    "IMotionDetector",
    "IVisionTracker",
    "ISceneAnalyzer",
    "IVisionPlannerContextBuilder",
    "IVisionSessionManager",
]
