"""Audio Intelligence Subsystem for ULTRON.

Provides provider-agnostic domain models, state machines, audio capture, VAD/STT/TTS/WakeWord configuration,
audio session manager orchestrator, voice planner gateway, audio playback abstractions, and abstract interfaces.
"""

from app.audio.adapters.real_stt import RealSTTProvider
from app.audio.adapters.real_tts import RealTTSProvider
from app.audio.adapters.sounddevice_capture import SoundDeviceCaptureAdapter
from app.audio.adapters.sounddevice_playback import SoundDevicePlaybackAdapter
from app.audio.base import (
    IAudioCapture,
    IAudioPlayback,
    IAudioSessionManager,
    ISpeechToTextProvider,
    ITextToSpeechProvider,
    IVoiceActivityDetector,
    IWakeWordDetector,
)
from app.audio.config import (
    AudioEngineConfig,
    create_stt_config,
    create_tts_config,
    create_vad_config,
    create_wake_word_config,
    get_audio_engine_config,
)
from app.audio.factory import AudioEngineFactory
from app.audio.models import (
    AudioChunk,
    AudioEncoding,
    AudioFormat,
    AudioPrivacy,
    AudioSessionState,
    AudioSessionStateMachine,
    AudioStreamConfig,
    AudioTelemetry,
    InvalidAudioStateTransitionError,
    PlaybackState,
    SpeechSynthesisRequest,
    SpeechSynthesisResult,
    Transcript,
    TranscriptSegment,
    VoiceActivityEvent,
    VoiceActivityState,
    WakeWordDetection,
)
from app.audio.planner_gateway import (
    IVoicePlannerGateway,
    PlannerStreamEvent,
    PlannerStreamEventType,
    VoiceGatewayCancelledError,
    VoiceGatewayConfigurationError,
    VoiceGatewayError,
    VoiceGatewayPlannerError,
    VoiceGatewayTimeoutError,
    VoicePlannerResponse,
)
from app.audio.playback import (
    PlaybackConfig,
    PlaybackDeviceNotFoundError,
    PlaybackError,
    PlaybackStateError,
    PlaybackTelemetry,
    PlaybackTimeoutError,
    PlaybackValidationError,
)
from app.audio.session import (
    AudioSessionConfig,
    AudioSessionError,
    AudioSessionLimitError,
    AudioSessionProcessingError,
    AudioSessionStateError,
    AudioSessionTelemetry,
    AudioSessionTimeoutError,
)
from app.audio.session_manager import AudioSessionManager
from app.audio.stt import (
    STTConfig,
    STTError,
    STTProcessingError,
    STTProviderError,
    STTTelemetry,
    STTTimeoutError,
    STTUnavailableError,
    STTValidationError,
)
from app.audio.tts import (
    TTSConfig,
    TTSError,
    TTSProcessingError,
    TTSProviderError,
    TTSTelemetry,
    TTSTimeoutError,
    TTSUnavailableError,
    TTSValidationError,
)
from app.audio.vad import (
    VADBackendError,
    VADConfig,
    VADConfigurationError,
    VADError,
    VADProcessingError,
    VADTelemetry,
    VADTimeoutError,
)
from app.audio.wake_word import (
    WakeWordConfig,
    WakeWordConfigurationError,
    WakeWordError,
    WakeWordProcessingError,
    WakeWordProviderError,
    WakeWordTelemetry,
    WakeWordTimeoutError,
    WakeWordUnavailableError,
    WakeWordValidationError,
)

__all__ = [
    "AudioEncoding",
    "AudioPrivacy",
    "AudioFormat",
    "AudioChunk",
    "AudioStreamConfig",
    "VoiceActivityState",
    "VoiceActivityEvent",
    "TranscriptSegment",
    "Transcript",
    "SpeechSynthesisRequest",
    "SpeechSynthesisResult",
    "WakeWordDetection",
    "AudioSessionState",
    "PlaybackState",
    "InvalidAudioStateTransitionError",
    "AudioSessionStateMachine",
    "AudioTelemetry",
    "VADConfig",
    "VADTelemetry",
    "VADError",
    "VADConfigurationError",
    "VADProcessingError",
    "VADBackendError",
    "VADTimeoutError",
    "STTConfig",
    "STTTelemetry",
    "STTError",
    "STTConfigurationError",
    "STTValidationError",
    "STTProviderError",
    "STTTimeoutError",
    "STTUnavailableError",
    "STTProcessingError",
    "TTSConfig",
    "TTSTelemetry",
    "TTSError",
    "TTSConfigurationError",
    "TTSValidationError",
    "TTSProviderError",
    "TTSTimeoutError",
    "TTSUnavailableError",
    "TTSProcessingError",
    "WakeWordConfig",
    "WakeWordTelemetry",
    "WakeWordError",
    "WakeWordConfigurationError",
    "WakeWordValidationError",
    "WakeWordProviderError",
    "WakeWordTimeoutError",
    "WakeWordUnavailableError",
    "WakeWordProcessingError",
    "AudioSessionConfig",
    "AudioSessionTelemetry",
    "AudioSessionError",
    "AudioSessionLimitError",
    "AudioSessionStateError",
    "AudioSessionTimeoutError",
    "AudioSessionProcessingError",
    "AudioSessionManager",
    "PlannerStreamEventType",
    "PlannerStreamEvent",
    "VoicePlannerResponse",
    "VoiceGatewayError",
    "VoiceGatewayConfigurationError",
    "VoiceGatewayPlannerError",
    "VoiceGatewayTimeoutError",
    "VoiceGatewayCancelledError",
    "PlaybackConfig",
    "PlaybackTelemetry",
    "PlaybackError",
    "PlaybackStateError",
    "PlaybackTimeoutError",
    "PlaybackValidationError",
    "PlaybackDeviceNotFoundError",
    "SoundDeviceCaptureAdapter",
    "SoundDevicePlaybackAdapter",
    "RealSTTProvider",
    "RealTTSProvider",
    "AudioEngineConfig",
    "AudioEngineFactory",
    "get_audio_engine_config",
    "create_vad_config",
    "create_wake_word_config",
    "create_stt_config",
    "create_tts_config",
    "IVoicePlannerGateway",
    "IAudioCapture",
    "IAudioPlayback",
    "IVoiceActivityDetector",
    "ISpeechToTextProvider",
    "ITextToSpeechProvider",
    "IWakeWordDetector",
    "IAudioSessionManager",
]
